behaviors:
  AgentBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    threaded: true
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 6000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

environment_parameters:
  lesson_id:
    curriculum:
        - name: lesson_1
          completion_criteria: 
            measure: reward
            behavior: AgentBehaviour
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 1
          value: 1.0
        - name: lesson_2
          completion_criteria: 
            measure: reward
            behavior: AgentBehaviour
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 1
          value: 2.0
        - name: lesson_3
          completion_criteria: 
            measure: reward
            behavior: AgentBehaviour
            signal_smoothing: true
            min_lesson_length: 100
            threshold: 1
          value: 3.0       